/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelos.Nivel;
import Modelos.Persona;
import Modelos.Usuario;
import Persistencia.DatabaseConnection;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rodrigososa
 */
public class PanelRegistroUsuario extends javax.swing.JPanel {

  /**
   * Creates new form RegistroPersona
   */
  DatabaseConnection connection = null;

  public PanelRegistroUsuario() {
    initComponents();
    try {
      connection = new DatabaseConnection();
    } catch (ClassNotFoundException | SQLException ex) {
      Logger.getLogger(PanelRegistroUsuario.class.getName()).log(Level.SEVERE, null, ex);
    }
    setUp();

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    nameEt = new javax.swing.JTextField();
    lastNameEt = new javax.swing.JTextField();
    emailEt = new javax.swing.JTextField();
    bannerEt = new javax.swing.JTextField();
    userEt = new javax.swing.JTextField();
    passwordEt = new javax.swing.JPasswordField();
    levelCb = new javax.swing.JComboBox<>();
    registerBtn = new javax.swing.JButton();

    setBackground(new java.awt.Color(59, 89, 152));

    jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Registrar a nuevo usuario");

    jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Nombre:");

    jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("Apellido:");

    jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setText("Correo:");

    jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("ID Banner:");

    jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setText("Usuario:");

    jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(255, 255, 255));
    jLabel7.setText("Contraseña:");

    jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(255, 255, 255));
    jLabel8.setText("Nivel:");

    registerBtn.setText("Registrar usuario");
    registerBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        registerBtnActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
              .addComponent(jLabel2)
              .addGap(18, 18, 18)
              .addComponent(nameEt))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3)
                .addComponent(jLabel4))
              .addGap(18, 18, 18)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(emailEt, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addComponent(lastNameEt))))
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addComponent(registerBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
              .addComponent(jLabel8)
              .addGap(18, 18, 18)
              .addComponent(levelCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
              .addComponent(jLabel7)
              .addGap(18, 18, 18)
              .addComponent(passwordEt))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5)
                .addComponent(jLabel6))
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(bannerEt, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addComponent(userEt)))))
        .addContainerGap(296, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(nameEt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(lastNameEt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(emailEt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(bannerEt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(userEt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7)
          .addComponent(passwordEt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel8)
          .addComponent(levelCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(registerBtn)
        .addContainerGap(108, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
    if (nameEt.getText().length() == 0
            || lastNameEt.getText().length() == 0
            || emailEt.getText().length() == 0
            || bannerEt.getText().length() == 0
            || userEt.getText().length() == 0
            || passwordEt.getText().length() == 0) {
      JOptionPane.showMessageDialog(this, "Debes llenar todos los campos correctamente");
    } else {
      try {
        Persona persona = new Persona(
                nameEt.getText().trim(),
                lastNameEt.getText().trim(),
                emailEt.getText().trim(),
                bannerEt.getText().trim(),
                LocalDate.now()
        );

        DatabaseConnection databaseConnection = new DatabaseConnection();
        long idPersona = persona.crearPersona(databaseConnection);
        ArrayList<Nivel> niveles = new Nivel().obtenerNiveles(databaseConnection);
        int nivelSeleccionado = 0;
        for(Nivel nivel: niveles) {
           if (levelCb.getSelectedItem().toString().equals(nivel.getNivel().toString())) {
            nivelSeleccionado = nivel.getNivel();
          }
        }
        if (idPersona != 0) {
          Usuario usuario = new Usuario(
                  userEt.getText().trim(),
                  passwordEt.getText().trim(),
                  nivelSeleccionado,
                  Integer.parseInt(String.valueOf(idPersona)),
                  LocalDate.now()
          );
           
          long idUsuario = usuario.crearUsuario(databaseConnection);
          if (idUsuario != 0) {
            JOptionPane.showMessageDialog(this, "Usuario creado correctamente");
          } else {
            JOptionPane.showMessageDialog(this, "Error guardando usuario");
          }
        } else {
          JOptionPane.showMessageDialog(this, "Error guardando persona");
        }
      } catch (SQLException | ClassNotFoundException ex) {
        Logger.getLogger(PanelRegistroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Error");
      }
    }
  }//GEN-LAST:event_registerBtnActionPerformed

  private void setUp() {
    try {
      Nivel nivelObj = new Nivel();
      try {
        ArrayList<Nivel> niveles = nivelObj.obtenerNiveles(new DatabaseConnection());
        if (niveles != null && niveles.size() > 0) {
          niveles.forEach((nivel) -> {
            switch (nivel.getNivel()) {
              case 0:
                levelCb.addItem("Administrativo");
                break;
              case 1:
                levelCb.addItem("Coordinador");
                break;
              case 2:
                levelCb.addItem("Estudiante");
                break;
            }
          });
        }
      } catch (SQLException ex) {
        Logger.getLogger(PanelRegistroUsuario.class.getName()).log(Level.SEVERE, null, ex);
      }
    } catch (ClassNotFoundException ex) {
      Logger.getLogger(PanelRegistroUsuario.class.getName()).log(Level.SEVERE, null, ex);
    }
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField bannerEt;
  private javax.swing.JTextField emailEt;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JTextField lastNameEt;
  private javax.swing.JComboBox<String> levelCb;
  private javax.swing.JTextField nameEt;
  private javax.swing.JPasswordField passwordEt;
  private javax.swing.JButton registerBtn;
  private javax.swing.JTextField userEt;
  // End of variables declaration//GEN-END:variables
}
