/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Persistencia.DatabaseConnection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rodrigososa
 */
public class PanelProyectos extends javax.swing.JPanel {

  /**
   * Creates new form PanelProyectos
   */
  public PanelProyectos() {
    initComponents();
    //bteliminar.setEnabled(false);
    llenarTabla(tabla, "proyecto");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btRegistro = new javax.swing.JButton();
        bteliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnDetalle = new javax.swing.JButton();

        setBackground(new java.awt.Color(59, 89, 152));

        jPanel1.setBackground(new java.awt.Color(59, 89, 152));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proyectos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuros/list.png"))); // NOI18N
        jButton1.setText("Listado");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);

        btRegistro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuros/add-user-symbol (1).png"))); // NOI18N
        btRegistro.setText("Registro");
        btRegistro.setBorder(null);
        btRegistro.setBorderPainted(false);
        btRegistro.setContentAreaFilled(false);
        btRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRegistro.setFocusPainted(false);
        btRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistroActionPerformed(evt);
            }
        });

        bteliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bteliminar.setForeground(new java.awt.Color(255, 255, 255));
        bteliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuros/delete.png"))); // NOI18N
        bteliminar.setText("Eliminar proyecto");
        bteliminar.setBorder(null);
        bteliminar.setBorderPainted(false);
        bteliminar.setContentAreaFilled(false);
        bteliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bteliminar.setFocusPainted(false);
        bteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bteliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btRegistro)
                    .addComponent(bteliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(59, 89, 152));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        btnDetalle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDetalle.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recuros/document.png"))); // NOI18N
        btnDetalle.setText("Detalle de proyecto");
        btnDetalle.setBorderPainted(false);
        btnDetalle.setContentAreaFilled(false);
        btnDetalle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDetalle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDetalle)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

  private void btRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistroActionPerformed
      //registro de proyecto!
      new Proyecto(null, true).setVisible(true);
  }//GEN-LAST:event_btRegistroActionPerformed

    private void bteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarActionPerformed
        int row = tabla.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar algun dato de la tabla");
        }
        else{
            int confirmar = JOptionPane.showConfirmDialog(null, "Estas seguro de eliminar esta fila");
            if (JOptionPane.OK_OPTION==confirmar) {
                //eliminar
                
            }
        }
    }//GEN-LAST:event_bteliminarActionPerformed

    private void btnDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleActionPerformed
        int row = tabla.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar algun dato de la tabla");
        }
        else{
            String id = (String) tabla.getValueAt(row, 2).toString();
            new Detalles(null, true, id).setVisible(true);
        }
    }//GEN-LAST:event_btnDetalleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegistro;
    private javax.swing.JButton bteliminar;
    private javax.swing.JButton btnDetalle;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
    public void llenarTabla(JTable jtabla, String tabla) {
        DatabaseConnection connection;
        String columnas[] = {"Ciclo°","Nombre del Proyecto", "ID", "Alumno","Cuatrimestre", "SRN°","Empresa"};
        String filas[][] = {};
        javax.swing.table.DefaultTableModel modelo = new DefaultTableModel(filas, columnas);
        Object datos[];
        try {
            connection = new DatabaseConnection();
            String query = "SELECT proyecto.uuid,nombre_proyecto,id_banner_alumno, nombre_alumno, cuatrimestre, carrera.nombre, empresa.nombre FROM proyecto INNER JOIN carrera ON carrera.id = proyecto.carrera INNER JOIN empresa ON empresa.id = proyecto.convenio";
            PreparedStatement preparedStatement = connection.getConnection().prepareStatement(query);
        
            ResultSet resultSet = preparedStatement.executeQuery();
                if (resultSet != null) {
                  //resultSet.next();
                    resultSet.beforeFirst();
                    while (resultSet.next()) {
                    datos = new Object[7];
                    datos[0] = resultSet.getString("proyecto.uuid");
                    datos[1] = resultSet.getString("nombre_proyecto");
                    datos[2] = resultSet.getString("id_banner_alumno");
                    datos[3] = resultSet.getString("nombre_alumno");
                    datos[4] = resultSet.getString("cuatrimestre");
                    datos[5] = resultSet.getString("carrera.nombre");
                    datos[6] = resultSet.getString("empresa.nombre");
                    
                    modelo.addRow(datos);
             //conn.Desconectar();
                  }
                }
            } catch (Exception e) {
            }
        jtabla.setModel(modelo);
        jScrollPane1.setViewportView(jtabla);
    }
}
